### ISSUE TITLE
Missing workshop.mustEmbedUnimplementedWorkshopServer and workshop.mustEmbedUnimplementedSubWorkshopServer  methods

### ISSUE THREAD

**Issue by ttyerl** [go-masonry/tutorial#3]
Hello, 
I'm at step 04-instrumentation.  When running ` go  run main.go config config/config.yml ` with files generated via the  latest **protoc** plugins I encountered the above errors. 

gRPC-Gateway version: grpc-gateway/v2@v2.5.0

protoc command line: `protoc -I"../../googleapis/" -I. --openapiv2_out . --openapiv2_opt logtostderr=true --grpc-gateway_out=repeated_path_param_separator=ssv:. --go_out=. --go_opt=paths=source_relative --go-grpc_out=. --go-grpc_opt=paths=source_relative garage.proto`

Resolution: the types within two files, listed below, were slightly changed:

app/controllers/workshop.go
```
type workshopController struct {
	deps    workshopControllerDeps
	client  *http.Client
	encoder *jsonpb.Marshaler
	workshop.UnimplementedWorkshopServer
}
```

app/controllers/subworkshop.go
```
type subWorkshopController struct {
	deps subWorkshopControllerDeps
	workshop.UnimplementedSubWorkshopServer
}
```

**Comment by talgendler** [comment]
Hi, the tutorial is a bit outdated, in terms of examples. You can try to work around it to make everything work for you or you can look at the service template and read https://go-masonry.github.io

**Comment by ttyerl** [comment]
Thanks for  the response and the tutorial! 

I'm co-opting the issue tracker with (hopefully) resolutions to issues I encountered for future reference.
